vim.keymap.set("n", "<leader>fb", function()
	Snacks.picker.buffers()
end, { desc = "Snacks: Find Buffer" })
vim.keymap.set("n", "<leader>fc", function()
	Snacks.picker.colorschemes()
end, { desc = "Snacks: Find Colorscheme" })
vim.keymap.set("n", "<leader>ff", function()
	Snacks.picker.files()
end, { desc = "Snacks: Find Files" })
vim.keymap.set("n", "<leader>fg", function()
	Snacks.picker.grep()
end, { desc = "Snacks: Find Grep" })
vim.keymap.set("n", "<leader>fh", function()
	Snacks.picker.help()
end, { desc = "Snacks: Find Help" })
vim.keymap.set("n", "<leader>fH", function()
	Snacks.picker.highlights()
end, { desc = "Snacks: Find Highlight" })
vim.keymap.set("n", "<leader>fi", function()
	Snacks.picker.icons()
end, { desc = "Snacks: Find Icons" })
vim.keymap.set("n", "<leader>fk", function()
	Snacks.picker.keymaps()
end, { desc = "Snacks: Find Keymap" })
vim.keymap.set("n", "<leader>fN", function()
	Snacks.picker.notifications()
end, { desc = "Snacks: Open Notifications" })
vim.keymap.set("n", "<leader>fu", function()
	Snacks.picker.undo()
end, { desc = "Snacks: Undo History" })
