return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	lazy = false,
	build = ":TSUpdate",
	dependencies = {
		{ "nvim-treesitter/nvim-treesitter-context", opts = {} },
	},
	config = function()
		local treesitter = require("nvim-treesitter")

		treesitter.install({
			"bash",
			"comment",
			"css",
			"csv",
			"dockerfile",
			"fish",
			"git_config",
			"git_rebase",
			"gitcommit",
			"gitignore",
			"html",
			"htmldjango",
			"http",
			"hyprlang",
			"javascript",
			"jinja",
			"jinja_inline",
			"json",
			"jsx",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"nginx",
			"python",
			"query",
			"regex",
			"requirements",
			"scss",
			"sql",
			"tmux",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"vue",
			"xml",
			"yaml",
		})
	end,
}
